# Generated by Django 4.1.6 on 2024-01-23 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('homeTeam', models.CharField(max_length=25)),
                ('awayTeam', models.CharField(max_length=25)),
                ('homeGoals', models.IntegerField()),
                ('awayGoals', models.IntegerField()),
                ('winner', models.CharField(max_length=5)),
                ('date_played', models.CharField(max_length=25)),
                ('referee', models.CharField(max_length=25)),
            ],
        ),
    ]
